/**
 * Mock Registry
 *
 * In a real implementation, this would be generated by bundler plugin
 * that reads all JSON files from __graphql_mocks__ directories.
 *
 * For this demo, we'll manually import and register mocks.
 */

// Import mock files (will be created later)
import GetCountryMocks from "../queries/__graphql_mocks__/GetCountry.json";
import GetCountriesMocks from "../queries/__graphql_mocks__/GetCountries.json";
import GetCountryWithPopulationMocks from "../queries/__graphql_mocks__/GetCountryWithPopulation.json";
import GetCountryWithWeatherMocks from "../queries/__graphql_mocks__/GetCountryWithWeather.json";

export const mockRegistry = {
  GetCountry: GetCountryMocks,
  GetCountries: GetCountriesMocks,
  GetCountryWithPopulation: GetCountryWithPopulationMocks,
  GetCountryWithWeather: GetCountryWithWeatherMocks,
};
